- name: "Set 24-hour time display"
  community.general.osx_defaults:
    domain: .GlobalPreferences
    key: AppleICUForce24HourTime
    type: int
    value: 1
  notify: Needs Reboot

- name: "Don't automatically rearrange spaces"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: int
    value: 0
  notify: Needs Reboot

- name: "Enable keyboard navigation to focus between controls"
  community.general.osx_defaults:
    domain: .GlobalPreferences
    key: AppleKeyboardUIMode
    type: int
    value: 2
  notify: Needs Reboot

- name: "Disable Spotlight hotkey"
  shell:
    cmd: '/usr/libexec/PlistBuddy -c "set AppleSymbolicHotKeys:64:enabled false"  ~/Library/Preferences/com.apple.symbolichotkeys.plist'
  register: spotlight_key_set_result
  check_mode: false
  changed_when: spotlight_key_set_result == 0
  ignore_errors: true

- name: "Add Spotlight hotkey dict"
  shell:
    cmd: '/usr/libexec/PlistBuddy -c "add AppleSymbolicHotKeys:64 dict" ~/Library/Preferences/com.apple.symbolichotkeys.plist'
  when: spotlight_key_set_result.rc != 0
  register: result
  check_mode: false
  changed_when: result == 0
  failed_when: result.rc != 0

- name: "Add Spotlight hotkey enabled bool"
  shell:
    cmd: '/usr/libexec/PlistBuddy -c "add AppleSymbolicHotKeys:64:enabled bool false" ~/Library/Preferences/com.apple.symbolichotkeys.plist'
  when: spotlight_key_set_result.rc != 0
  register: result
  check_mode: false
  changed_when: result == 0
  failed_when: result.rc != 0

- name: "Add Spotlight hotkey value dict"
  shell:
    cmd: '/usr/libexec/PlistBuddy -c "add AppleSymbolicHotKeys:64:value dict" ~/Library/Preferences/com.apple.symbolichotkeys.plist'
  when: spotlight_key_set_result.rc != 0
  register: result
  check_mode: false
  changed_when: result == 0
  failed_when: result.rc != 0

- name: "Add Spotlight hotkey value type string"
  shell:
    cmd: '/usr/libexec/PlistBuddy -c "add AppleSymbolicHotKeys:64:value:type string standard" ~/Library/Preferences/com.apple.symbolichotkeys.plist'
  when: spotlight_key_set_result.rc != 0
  register: result
  check_mode: false
  changed_when: result == 0
  failed_when: result.rc != 0

- name: "Add Spotlight hotkey value parameters array"
  shell:
    cmd: '/usr/libexec/PlistBuddy -c "add AppleSymbolicHotKeys:64:value:parameters array" ~/Library/Preferences/com.apple.symbolichotkeys.plist'
  when: spotlight_key_set_result.rc != 0
  register: result
  check_mode: false
  changed_when: result == 0
  failed_when: result.rc != 0

- name: "Add Spotlight hotkey value parameters array value 1"
  shell:
    cmd: '/usr/libexec/PlistBuddy -c "add AppleSymbolicHotKeys:64:value:parameters:0 integer 65535" ~/Library/Preferences/com.apple.symbolichotkeys.plist'
  when: spotlight_key_set_result.rc != 0
  register: result
  check_mode: false
  changed_when: result == 0
  failed_when: result.rc != 0

- name: "Add Spotlight hotkey value parameters array value 2"
  shell:
    cmd: '/usr/libexec/PlistBuddy -c "add AppleSymbolicHotKeys:64:value:parameters:0 integer 49" ~/Library/Preferences/com.apple.symbolichotkeys.plist'
  when: spotlight_key_set_result.rc != 0
  register: result
  check_mode: false
  changed_when: result == 0
  failed_when: result.rc != 0

- name: "Add Spotlight hotkey value parameters array value 3"
  shell:
    cmd: '/usr/libexec/PlistBuddy -c "add AppleSymbolicHotKeys:64:value:parameters:0 integer 1048576" ~/Library/Preferences/com.apple.symbolichotkeys.plist'
  when: spotlight_key_set_result.rc != 0
  register: result
  check_mode: false
  changed_when: result == 0
  failed_when: result.rc != 0

- name: "Enable Trackpad tap-to-click"
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: int
    value: 1
  notify: Needs Reboot

- name: "Configure bottom right hot corner to lock screen"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-br-corner
    type: int
    value: 13
  notify: Restart Dock

- name: "Set Dock default size"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 16
  notify: Restart Dock
  
- name: "Set Dock zoom enabled"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: int
    value: 1
  notify: Restart Dock

- name: "Set Dock zoom size"
  community.general.osx_defaults:
    domain: com.apple.dock
    key: largesize
    type: float
    value: 33
  notify: Restart Dock

- name: "Show status bar in Finder"
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: int
    value: 1


# Bind apps to all spaces

- name: "Add app-bindings dict to com.apple.spaces"
  shell:
    cmd: '/usr/libexec/PlistBuddy -c "add app-bindings dict" ~/Library/Preferences/com.apple.spaces.plist'
  register: result
  check_mode: false
  changed_when: result == 0
  failed_when: result.rc != 0
  ignore_errors: true

- name: "Remove any current app:space bindings"
  shell:
    cmd: "/usr/libexec/PlistBuddy -c 'delete app-bindings:{{ item }}' ~/Library/Preferences/com.apple.spaces.plist"
  register: result
  check_mode: false
  changed_when: result == 0
  failed_when: result.rc != 0
  with_items: 
    - "{{ all_space_apps }}"
  ignore_errors: true

- name: "Bind apps to all spaces"
  shell:
    cmd: "/usr/libexec/PlistBuddy -c 'add app-bindings:{{ item }} string AllSpaces' ~/Library/Preferences/com.apple.spaces.plist"
  register: result
  check_mode: false
  changed_when: result == 0
  failed_when: result.rc != 0
  with_items: 
    - "{{ all_space_apps }}"
